In [117]:
# Load all the pickle files in P folder which contains rfecv.pkl in the name
# Load the files in the list

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import average_precision_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import auc
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import average_precision_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
import pickle

rfecv = []
for number in range(1, 15):
    p = pickle.load(open('P/m_'+str(number)+'rfecv.pkl', 'rb'))
    rfecv.append(p)

df=pd.read_csv('Class/binaryAllNaturalPlusNormalVsAttacks/data1.csv')
# Preprocess the test data
df = preprocess(df)
# Remove irrelevant features
df = remove_irrelevant_features(df)
# Vectorize the test data
df = vectorize_df(df)
# Remove irrelevant features
features_list = df.columns.to_list()
if 'marker' in features_list:
    features_list.remove('marker')
if 'index' in features_list:
    features_list.remove('index')
X = df[features_list]


# Print the optimal feature names for each model as list
for i in range(len(rfecv)):
    if i==(len(rfecv)-1):
        p = ""
    else:
        p = ","
    print(str(X.columns[rfecv[i].support_].tolist())+""+p)

/home/nonofurbuisness/.local/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 1.1.2 when using version 1.1.3. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/nonofurbuisness/.local/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 1.1.2 when using version 1.1.3. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/nonofurbuisness/.local/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator RFECV from version 1.1.2 when using version 1.1.3. This might lead to brea

['R1-PA2:VH', 'R1-PM5:I', 'R2-PM5:I', 'R2-PA7:VH', 'R3-PA3:VH', 'R3-PA6:IH', 'R3-PA7:VH', 'R4-PA2:VH', 'R4-PM5:I'],
['R1-PA2:VH', 'R1-PA3:VH', 'R1-PA5:IH', 'R1-PM5:I', 'R2-PA3:VH', 'R2-PM3:V', 'R2-PM5:I', 'R2-PA7:VH', 'R3-PA5:IH', 'R3-PM5:I', 'R3-PA7:VH', 'R4-PM2:V', 'R4-PA5:IH', 'R4-PM5:I'],
['R1-PA2:VH', 'R1-PA3:VH', 'R1-PM5:I', 'R2-PA5:IH', 'R2-PM5:I', 'R3-PA1:VH', 'R3-PA2:VH', 'R3-PM2:V', 'R3-PA3:VH', 'R3-PA5:IH', 'R3-PM5:I', 'R4-PM2:V', 'R4-PA3:VH', 'R4-PM5:I'],
['R1-PA1:VH', 'R1-PA2:VH', 'R1-PA3:VH', 'R1-PM5:I', 'R1-PA7:VH', 'R2-PA5:IH', 'R2-PM5:I', 'R3-PM5:I', 'R4-PA2:VH', 'R4-PM2:V', 'R4-PM5:I'],
['R1-PA3:VH', 'R1-PA5:IH', 'R1-PM5:I', 'R1-PA7:VH', 'R2-PM1:V', 'R2-PA2:VH', 'R2-PA5:IH', 'R2-PM5:I', 'R2-PM6:I', 'R3-PA2:VH', 'R3-PA3:VH', 'R3-PA5:IH', 'R3-PM5:I', 'R4-PA1:VH', 'R4-PM2:V', 'R4-PA3:VH', 'R4-PM5:I', 'R4-PA7:VH'],
['R1-PA2:VH', 'R1-PA5:IH', 'R1-PM5:I', 'R2-PA2:VH', 'R2-PA3:VH', 'R2-PM3:V', 'R2-PA5:IH', 'R2-PM5:I', 'R3-PA2:VH', 'R3-PA5:IH', 'R3-PM5:I', 'R4-PA2:VH', 'R4-PM

In [9]:
def preprocess(df):
    apparent_impedance_measurements_headers_names = ['R1-PA:Z', 'R2-PA:Z', 'R3-PA:Z', 'R4-PA:Z']
    voltage_phase_angles_headers_names = ['R1-PA1:VH', 'R1-PA2:VH', 'R1-PA3:VH',
                                      'R2-PA1:VH', 'R2-PA2:VH', 'R2-PA3:VH',
                                      'R3-PA1:VH', 'R3-PA2:VH', 'R3-PA3:VH',
                                      'R4-PA1:VH', 'R4-PA2:VH', 'R4-PA3:VH']
    current_phase_angles_headers_names = ['R1-PA4:IH', 'R1-PA5:IH', 'R1-PA6:IH',
                                      'R2-PA4:IH', 'R2-PA5:IH', 'R2-PA6:IH',
                                      'R3-PA4:IH', 'R3-PA5:IH', 'R3-PA6:IH',
                                      'R4-PA4:IH', 'R4-PA5:IH', 'R4-PA6:IH']
    voltage_phase_magnitudes_headers_names = ['R1-PM1:V', 'R1-PM2:V', 'R1-PM3:V',
                                          'R2-PM1:V', 'R2-PM2:V', 'R2-PM3:V',
                                          'R3-PM1:V', 'R3-PM2:V', 'R3-PM3:V',
                                          'R4-PM1:V', 'R4-PM2:V', 'R4-PM3:V']
    current_phase_magnitudes_header_names = ['R1-PM4:I', 'R1-PM5:I', 'R1-PM6:I',
                                         'R2-PM4:I', 'R2-PM5:I', 'R2-PM6:I',
                                         'R3-PM4:I', 'R3-PM5:I', 'R3-PM6:I',
                                         'R4-PM4:I', 'R4-PM5:I', 'R4-PM6:I']

    # Apparent Impedance measurements for each relay (R1-PA:Z, R2-PA:Z, R3-PA:Z, R4-PA:Z), having values in the 4.8 to 4.9 range
    for header in apparent_impedance_measurements_headers_names:
        df[header+'_in_range(4.8-4.9)'] = np.where((df[header] >= 4.8) & (df[header] <= 4.9), 1, 0)

    # Voltage Phase Angles (PA1:VH – PA3:VH) in the 3.0 range
    for header in voltage_phase_angles_headers_names:
        df[header + '_in_range(3.0)'] = np.where(abs(df[header]-3.0) <= 0.5, 1, 0)

    # Current Phase Angles (PA4:IH – PA6:IH) in the 3.0 range
    for header in current_phase_angles_headers_names:
        df[header + '_in_range(3.0)'] = np.where(abs(df[header]-3.0) <= 0.5, 1, 0)

    # Voltage Phase Magnitudes (PM1:V – PM3:V) in the 3.0 range
    for header in voltage_phase_magnitudes_headers_names:
        df[header + '_in_range(3.0)'] = np.where(abs(df[header]-3.0) <= 0.5, 1, 0)

    # Current Phase Magnitudes (PM4:I – PM6:I) in the 3.0 range
    for header in current_phase_magnitudes_header_names:
        df[header + '_in_range(3.0)'] = np.where(abs(df[header]-3.0) <= 0.5, 1, 0)
    

    return df

In [75]:
from sklearn.preprocessing import LabelEncoder, StandardScaler, QuantileTransformer, RobustScaler, MinMaxScaler, FunctionTransformer
# LabelEncoder encodes labels with a value between 0 and n_classes-1
le = LabelEncoder()
# StandardScaler scales values by subtracting the mean and dividing by the standard deviation
ss = StandardScaler()
# QuantileTransformer transforms features using quantiles information
qt = QuantileTransformer()
# RobustScaler scales values by subtracting the median and dividing by the interquartile range
rs = RobustScaler()
# MinMaxScaler scales values between 0 and 1
mms = MinMaxScaler()
# LogTransformer transforms features by taking the natural logarithm
lt = FunctionTransformer(np.log1p)
def vectorize_df(df):
    df_numeric = df.select_dtypes(include=[np.number])
    # Perform label encoder on marked column
    df['marker'] = le.fit_transform(df['marker'])
    for column in df_numeric.columns:
        if column == 'marker':
            continue
        column_data = df_numeric[column]
        # To avoid Input X contains infinity or a value too large for dtype('float64') error we replace them with float.max
        column_data = column_data.replace(
            [np.inf, -np.inf], np.finfo(np.float64).max)
        # Check if the data is normally distributed
        if column_data.skew() < 0.5:
            df_numeric[column] = ss.fit_transform(
                column_data.values.reshape(-1, 1))
        # Check if the data has extreme outliers
        elif column_data.quantile(0.25) < -3 or column_data.quantile(0.75) > 3:
            df_numeric[column] = rs.fit_transform(
                column_data.values.reshape(-1, 1))
        # Check if the data has a Gaussian-like distribution
        elif 0.5 < column_data.skew() < 1:
            df_numeric[column] = lt.fit_transform(
                column_data.values.reshape(-1, 1))
        # Check if the data can be transformed into a Gaussian-like distribution
        elif column_data.skew() > 1:
            df_numeric[column] = qt.fit_transform(
                column_data.values.reshape(-1, 1))
        else:
            df_numeric[column] = mms.fit_transform(
                column_data.values.reshape(-1, 1))
            df[df_numeric.columns] = df_numeric
    return df

In [73]:
def remove_irrelevant_features(df):
    # Remove all NAN columns or replace with desired string
    # This loop iterates over all of the column names which are all NaN
    for column in df.columns[df.isna().any()].tolist():
        # df.drop(column, axis=1, inplace=True)
        df[column] = df[column].fillna(0.0)

    df = df.replace([np.inf, -np.inf], np.nan)
    df = df.dropna()
    df = df.reset_index()
    return df

In [129]:
data = []
for i in range (1,15):
    df = pd.read_csv('Class/binaryAllNaturalPlusNormalVsAttacks/data'+str(i)+'.csv')
    df = preprocess(df)
    df = vectorize_df(df)
    df = remove_irrelevant_features(df)
    df['Label']=np.full_like(df['R1-PA:Z'], i)
    data.append(df)
df = pd.concat(data)

/home/nonofurbuisness/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/nonofurbuisness/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/nonofurbuisness/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/nonofurbuisness/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/nonofurbuisness/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/nonofurbuisness/.local/lib/py

In [130]:
# Save df to csv
df.to_csv('Class/binaryAllNaturalPlusNormalVsAttacks/df.csv', index=False)

In [131]:
df 

index   R1-PA1:VH     R1-PM1:V   R1-PA2:VH     R1-PM2:V   R1-PA3:VH  \
0         0   70.399324  127673.0908  -49.572308  127648.0176 -169.578319   
1         1   73.688102  130280.7109  -46.300719  130255.6377 -166.278082   
2         2   73.733939  130305.7842  -46.254883  130280.7109 -166.232245   
3         3   74.083443  130581.5902  -45.899649  130556.5169 -165.882741   
4         4   74.553268  131083.0556  -45.424094  131057.9823 -165.424375   
...     ...         ...          ...         ...          ...         ...   
4689   5110 -119.696613  131308.7150  120.326867  131258.5685    0.309397   
4690   5111 -119.742450  131333.7883  120.286760  131308.7150    0.269290   
4691   5112 -119.765368  131383.9348  120.258112  131333.7883    0.246372   
4692   5113 -119.828393  131484.2279  120.200816  131434.0813    0.183346   
4693   5114 -119.931526  131634.6675  120.097683  131609.5942    0.085944   

         R1-PM3:V   R1-PA4:IH   R1-PM4:I   R1-PA5:IH  ...  \
0     127723.2374   65.689611  605.91099  -57.003571  ...   
1     130355.9307   71.831719  483.59351  -50.947407  ...   
2     130381.0040   71.808800  483.59351  -50.913030  ...   
3     130656.8100   72.152575  482.86107  -50.437475  ...   
4     131158.2754   72.118198  484.50906  -50.013486  ...   
...           ...         ...        ...         ...  ...   
4689  131358.8615 -116.235948  337.65484  122.045740  ...   
4690  131383.9348 -116.510968  338.02106  121.885312  ...   
4691  131434.0813 -116.740151  339.66905  121.696236  ...   
4692  131509.3012 -117.536562  342.41570  121.054523  ...   
4693  131709.8873 -118.602264  346.26101  120.200816  ...   

      R2-PM4:I_in_range(3.0)  R2-PM5:I_in_range(3.0)  R2-PM6:I_in_range(3.0)  \
0                          0                       0                       0   
1                          0                       0                       0   
2                          0                       0                       0   
3                          0                       0                       0   
4                          0                       0                       0   
...                      ...                     ...                     ...   
4689                       0                       0                       0   
4690                       0                       0                       0   
4691                       0                       0                       0   
4692                       0                       0                       0   
4693                       0                       0                       0   

      R3-PM4:I_in_range(3.0)  R3-PM5:I_in_range(3.0)  R3-PM6:I_in_range(3.0)  \
0                          0                       0                       0   
1                          0                       0                       0   
2                          0                       0                       0   
3                          0                       0                       0   
4                          0                       0                       0   
...                      ...                     ...                     ...   
4689                       0                       0                       0   
4690                       0                       0                       0   
4691                       0                       0                       0   
4692                       0                       0                       0   
4693                       0                       0                       0   

      R4-PM4:I_in_range(3.0)  R4-PM5:I_in_range(3.0)  R4-PM6:I_in_range(3.0)  \
0                          0                       0                       0   
1                          0                       0                       0   
2                          0                       0                       0   
3                          0                       0                       0   
4                         

In [133]:
# Random forest classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV

rfc = RandomForestClassifier(n_estimators=20)

# Split the data into training and testing sets
X = df.drop(['Label','marker','index'], axis=1)
y = df['Label']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Fit the model
rfc.fit(X_train, y_train)

# Predict the model
y_pred = rfc.predict(X_test)

# Evaluate the model
print('Accuracy: ', accuracy_score(y_test, y_pred))
print('Confusion Matrix: ', confusion_matrix(y_test, y_pred))

Accuracy:  0.8387504648568241
Confusion Matrix:  [[776   9   6  11  20  10  10  10  10  13   8   8   8  11]
 [ 13 782  10  16  15   5   8  14  19  14   8  11   9  12]
 [  5  20 821   8  17  14  10   9  12  12  21  11   3   5]
 [ 14  10  11 805   9   9  13  11  10   5  10   8   7   6]
 [ 15  10   6  25 792   8  14   5  13  12   7   7  17   5]
 [  9  17  13  11  15 784  11  10  14  12   6  10  13   4]
 [ 18  13  10  15  18  18 826   4  18  10  12  11   8  14]
 [ 14  13  14  12   7  10  15 816  14   7  14   8   8   6]
 [ 12  17  20  17  11  18   8  15 820   7  13  10   8  13]
 [ 23  13   9  11  16   9  16   8  15 906  16  18  13   5]
 [  6  18  22  12  15  12  14   9  13  12 793  14   9   8]
 [ 14  10  15  18   8  13  13  12  10  11  13 769  10  10]
 [ 22  14  11  14  18  15   8  16  15  10  13  11 839  13]
 [ 17  14  17  12  20   9  11   8  20   7   9  10  14 748]]


In [ ]:
# Sava the model
import pickle
pickle.dump(rfc, open('P/router.pkl', 'wb'))